name: StyleID
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - brotli-python=1.0.9=py38h6a678d5_8
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.12.2=h06a4308_0
  - certifi=2024.8.30=py38h06a4308_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - ffmpeg=4.2.2=h20bf706_0
  - freetype=2.13.3=h4a9f257_0
  - gmp=6.3.0=h6a678d5_0
  - gnutls=3.6.15=he1e5248_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - jpeg=9f=h5ce9db8_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.16=hb9589c4_0
  - ld_impl_linux-64=2.44=h153f514_2
  - lerc=4.0.0=h6a678d5_0
  - libdeflate=1.22=h5eee18b_0
  - libffi=3.3=he6710b0_2
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgfortran=15.2.0=h166f726_7
  - libgfortran-ng=15.2.0=h166f726_7
  - libgfortran5=15.2.0=hc633d37_7
  - libgomp=15.2.0=h4751f2c_7
  - libidn2=2.3.4=h5eee18b_0
  - libopus=1.3.1=h5eee18b_1
  - libpng=1.6.50=h2ed474d_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libtasn1=4.21.0=h27ab2c4_0
  - libtiff=4.5.1=hffd6297_1
  - libunistring=0.9.10=h27cfd23_0
  - libuv=1.48.0=h5eee18b_0
  - libvpx=1.7.0=h439df22_0
  - libwebp-base=1.6.0=hb7bb969_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - lz4-c=1.9.4=h6a678d5_1
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py38h7f8727e_0
  - mkl_fft=1.3.1=py38hd3c417c_0
  - mkl_random=1.2.2=py38h51133e4_0
  - ncurses=6.5=h7934f7d_0
  - nettle=3.7.3=hbbd107a_1
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.2=he7f1fd0_0
  - openssl=1.1.1w=h7f8727e_0
  - pillow=10.4.0=py38h5eee18b_0
  - pip=20.3.3=py38h06a4308_0
  - pthread-stubs=0.3=h0ce48e5_1
  - pysocks=1.7.1=py38h06a4308_0
  - python=3.8.5=h7579374_1
  - pytorch=1.11.0=py3.8_cuda11.3_cudnn8.2.0_0
  - pytorch-mutex=1.0=cuda
  - readline=8.3=hc2a1206_0
  - setuptools=75.1.0=py38h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.51.1=he0a8d7e_0
  - tk=8.6.15=h54e0aa7_0
  - torchvision=0.12.0=py38_cu113
  - typing_extensions=4.11.0=py38h06a4308_0
  - wheel=0.44.0=py38h06a4308_0
  - x264=1!157.20191217=h7b6447c_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=h11fc155_0
  - pip:
      - absl-py==2.3.1
      - accelerate==1.0.1
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.10.11
      - aiosignal==1.3.1
      - albumentations==0.4.3
      - altair==5.4.1
      - antlr4-python3-runtime==4.8
      - anyio==4.5.2
      - astor==0.8.1
      - async-timeout==5.0.1
      - attrs==25.3.0
      - backports-zoneinfo==0.2.1
      - base58==2.1.1
      - blinker==1.8.2
      - cachetools==5.5.2
      - chardet==3.0.4
      - click==8.1.8
      - contourpy==1.1.1
      - cycler==0.12.1
      - diffusers==0.25.1
      - einops==0.3.0
      - exceptiongroup==1.3.1
      - filelock==3.16.1
      - fonttools==4.57.0
      - frozenlist==1.5.0
      - fsspec==2025.3.0
      - ftfy==6.2.3
      - future==1.0.0
      - gitdb==4.0.12
      - gitpython==3.1.46
      - google-auth==2.47.0
      - google-auth-oauthlib==1.0.0
      - grpcio==1.70.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.23.5
      - idna==2.10
      - imageio==2.9.0
      - imageio-ffmpeg==0.4.2
      - imgaug==0.2.6
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - invisible-watermark==0.2.0
      - jinja2==3.1.6
      - joblib==1.4.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - kiwisolver==1.4.7
      - kornia==0.6.0
      - lazy-loader==0.4
      - lpips==0.1.4
      - markdown==3.7
      - markupsafe==2.1.5
      - matplotlib==3.7.5
      - multidict==6.1.0
      - narwhals==1.42.1
      - networkx==3.1
      - numpy==1.24.4
      - oauthlib==3.3.1
      - omegaconf==2.1.1
      - opencv-python==4.1.2.30
      - opencv-python-headless==4.12.0.88
      - packaging==25.0
      - pandas==2.0.3
      - pkgutil-resolve-name==1.3.10
      - propcache==0.2.0
      - protobuf==5.29.5
      - psutil==7.2.1
      - pudb==2019.2
      - pyarrow==17.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pydeck==0.9.1
      - pydeprecate==0.3.1
      - pygments==2.19.2
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - pytorch-lightning==1.4.2
      - pytz==2025.2
      - pywavelets==1.4.1
      - pyyaml==6.0.3
      - referencing==0.35.1
      - regex==2024.11.6
      - requests==2.24.0
      - requests-oauthlib==2.0.0
      - rpds-py==0.20.1
      - rsa==4.9.1
      - safetensors==0.5.3
      - scikit-image==0.20.0
      - scikit-learn==1.1.1
      - scipy==1.9.1
      - smmap==5.0.2
      - sniffio==1.3.1
      - streamlit==0.73.1
      - tensorboard==2.14.0
      - tensorboard-data-server==0.7.2
      - test-tube==0.7.5
      - threadpoolctl==3.5.0
      - tifffile==2023.7.10
      - timm==1.0.24
      - tokenizers==0.15.2
      - toml==0.10.2
      - torch-fidelity==0.3.0
      - torchmetrics==0.6.0
      - tornado==6.4.2
      - tqdm==4.67.1
      - transformers==4.39.3
      - tzdata==2025.3
      - tzlocal==5.2
      - urllib3==1.25.11
      - urwid==2.6.16
      - validators==0.34.0
      - watchdog==4.0.2
      - wcwidth==0.2.14
      - werkzeug==3.0.6
      - yarl==1.15.2
      - zipp==3.20.2
prefix: /home/cognition/miniconda3/envs/StyleID
